#include "WatchButtonFeedback.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <vector>

static void appendRun(std::vector<uint8_t>& encoded, uint8_t kind,
                      size_t length, uint8_t value = 0) {
    encoded.push_back((uint8_t)((kind << 6) | (length - 1)));
    if (kind == 3) encoded.push_back(value);
}

static std::vector<uint8_t> encode(const std::vector<uint8_t>& input) {
    std::vector<uint8_t> encoded;
    size_t pos = 0;
    while (pos < input.size()) {
        size_t repeat = 1;
        while (pos + repeat < input.size() && repeat < 64
               && input[pos + repeat] == input[pos]) ++repeat;
        if (repeat >= 3) {
            uint8_t kind = input[pos] == 0 ? 1 : input[pos] == 255 ? 2 : 3;
            appendRun(encoded, kind, repeat, input[pos]);
            pos += repeat;
            continue;
        }
        size_t literal = 0;
        do {
            ++literal;
            if (literal == 64 || pos + literal == input.size()) break;
            repeat = 1;
            while (pos + literal + repeat < input.size() && repeat < 3
                   && input[pos + literal + repeat] == input[pos + literal]) ++repeat;
        } while (repeat < 3);
        appendRun(encoded, 0, literal);
        encoded.insert(encoded.end(), input.begin() + pos,
                       input.begin() + pos + literal);
        pos += literal;
    }
    return encoded;
}

int main(int argc, char** argv) {
    if (argc != 2) {
        fprintf(stderr, "usage: %s OUTPUT_HEADER\n", argv[0]);
        return 2;
    }
    std::vector<uint8_t> decoded;
    const watchbuttons::Button buttons[] = {
        watchbuttons::A, watchbuttons::B, watchbuttons::Power
    };
    for (auto button : buttons) {
        auto bounds = watchbuttons::dirtyBounds(button);
        for (uint8_t step = 0; step <= watchbuttons::Feedback::ExpandSteps; ++step) {
            auto blob = watchbuttons::expandedBlob(button, step);
            for (int16_t y = 0; y < bounds.h; ++y)
                for (int16_t x = 0; x < bounds.w; ++x)
                    decoded.push_back(watchbuttons::blobCoverage(
                        blob, bounds.x + x + 0.5f, bounds.y + y + 0.5f));
        }
    }
    std::vector<uint8_t> encoded = encode(decoded);
    FILE* out = fopen(argv[1], "wb");
    if (!out) {
        perror(argv[1]);
        return 1;
    }
    fprintf(out, "// Generated by tools/generate_button_feedback_masks.cpp; do not edit.\n");
    fprintf(out, "#pragma once\n\n#include <stddef.h>\n#include <stdint.h>\n\n");
    fprintf(out, "namespace watchbuttonmasks {\n");
    fprintf(out, "constexpr size_t DecodedSize = %zu;\n", decoded.size());
    fprintf(out, "constexpr size_t EncodedSize = %zu;\n", encoded.size());
    fprintf(out, "static const uint8_t Encoded[EncodedSize] = {\n");
    for (size_t i = 0; i < encoded.size(); ++i) {
        if (i % 16 == 0) fprintf(out, "    ");
        fprintf(out, "0x%02X%s", encoded[i], i + 1 == encoded.size() ? "" : ",");
        fprintf(out, i % 16 == 15 || i + 1 == encoded.size() ? "\n" : " ");
    }
    fprintf(out, "};\n} // namespace watchbuttonmasks\n");
    fclose(out);
    fprintf(stderr, "encoded %zu mask bytes as %zu bytes (%.1f%%)\n",
            decoded.size(), encoded.size(), encoded.size() * 100.0 / decoded.size());
    return 0;
}
