#!/usr/bin/env python3
"""Rebuild native 4-bit coverage atlases. Usage: generate_fonts.py NotoSansSC.ttf"""
from pathlib import Path
import hashlib
import sys
from PIL import Image, ImageDraw, ImageFont
root = Path(__file__).resolve().parents[1]
source = Path(sys.argv[1])
latin = ''.join(chr(i) for i in range(32,127))
corpus = (root/'fonts/corpus.txt').read_text()
faces = [
    ('Latin14',14,latin),('Latin18',18,latin),('Latin24',24,latin),
    ('Latin28',28,latin),('Clock36',36,' 0123456789:/APM?'),
    ('Cjk18',18,latin+corpus),('Cjk22',22,latin+corpus),
    ('Cjk24',24,latin+corpus),('Cjk28',28,latin+corpus),
]
for name,size,chars in faces:
    font = ImageFont.truetype(str(source),size)
    font.set_variation_by_name('Regular')
    ascent,descent = font.getmetrics()
    data=[]; glyphs=[]
    for ch in sorted(set(chars)-{'\n'},key=ord):
        # Anchor to baseline, then shift all glyphs to a stable common line box.
        x0,y0,x1,y1 = font.getbbox(ch,anchor='ls')
        width,height=x1-x0,y1-y0
        img=Image.new('L',(max(width,1),max(height,1)),0)
        ImageDraw.Draw(img).text((-x0,-y0),ch,font=font,fill=255,anchor='ls')
        values=[round(p/17) for p in img.get_flattened_data()] if width*height else []
        if len(values)%2: values.append(0)
        offset=len(data); data.extend((values[i]<<4)|values[i+1] for i in range(0,len(values),2))
        # Noto's vertical metrics exceed the visual em. Baseline at size+1.
        glyphs.append((ord(ch),offset,x0,y0+size+1,width,height,round(font.getlength(ch))))
    lines=['// Generated by tools/generate_fonts.py; font coverage licensed OFL-1.1.','#include "UxText.h"','namespace ux {','namespace {','const uint8_t pixels[] = {']
    lines.extend('  '+','.join(str(x) for x in data[i:i+32])+',' for i in range(0,len(data),32))
    lines+=['};','const Glyph glyphs[] = {']+['  {'+','.join(map(str,g))+'},' for g in glyphs]+['};','}',f'extern const Font {name} = {{glyphs,pixels,{len(glyphs)},{size+5}}};','}']
    (root/f'src/Font{name}.cpp').write_text('\n'.join(lines)+'\n')
    print(name,len(glyphs),'glyphs,',len(data),'coverage bytes')
(root/'fonts/source.sha256').write_text(hashlib.sha256(source.read_bytes()).hexdigest()+'  NotoSansSC[wght].ttf\n')
